interface Example {
    void fun_a(in float d);
    int fun_b(in int i);
    future<var> getitem(in text k);
    int sum(in list<int> nums);
    list<int> graph(in time t);
    void print(in var value);
    void setProxy(in Example* ep);
    future<Example*> getProxy();
};
